### PR TITLE
NCHK-4651 Initial implmentation

### PR DESCRIPTION
**Pull request by lnewman-book**
@brucemackenzie @otyaglo

### CODE REVIEW

**Comment by brucemackenzie** [comment]
Should we also update the Read.me?
`Currently supported methods of input/output:
Redis {format => 'json_event'}
RabbitMQ {mechanism => PLAIN}`

**Comment by bitwiseman** [comment]
Yes, I should also update readme.

**Comment by lnewman-book** [comment]
Okay, updated.  I'm pretty satisfied with it now.

**Comment by lnewman-book** [comment]
I think I'll be going back to using the Exception utils...
https://github.com/bnedu/logstash-plugin/commit/718dddef730d78182272a9cf00850a85bf78acd4
Using exception utils the output is:
```
Removing config files: 
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:395)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:354)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at jenkins.plugins.logstash.persistence.ElasticSearchDao.push(ElasticSearchDao.java:100)
	at jenkins.plugins.logstash.LogstashNotifier.perform(LogstashNotifier.java:109)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:182)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)
	at hudson.model.Run.execute(Run.java:1731)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:232)

[logstash-plugin]: Failed to send log data to ELASTICSEARCH:https://nere-dev-es01.yuzu-es.com:443.
Build step 'Send console log to Logstash' marked build as failure
Finished: FAILURE
```


https://github.com/bnedu/logstash-plugin/commit/180fd81212aafbdb6b8ba74b452fe2d347b42037
Without exception utils the output is:
```
Removing config files: 
java.net.SocketException: Connection reset
[logstash-plugin]: Failed to send log data to ELASTICSEARCH:https://nere-dev-es01.yuzu-es.com:-1.
Build step 'Send console log to Logstash' marked build as failure
Finished: FAILURE
```

**Comment by brucemackenzie** [comment]
I wasn't very clear. I believe you want both. You want the stacktrace AND the message.
Two log messages is ok in such a failure.

**Comment by brucemackenzie** [comment]
LGTM.

**Pull request merged**
